{ config, pkgs, ... }:

{
  # Import other configuration modules
  # (hardware-configuration.nix is autogenerated upon installation)
  # paths in nix expressions are always relative the file which defines them
  imports =
    [
      # ./hardware-configuration.nix
      ./boot.nix
      ./common.nix
      ./desktop.nix
      ./machine/vm.nix
    ];
}
