### KEYBINDINGS ###
# Basic window management
drag_tile_to_tile=1
keymode=common
bind=SUPER,F5,reload_config

bind=SUPER,Delete,killclient
bind=SUPER,f,togglefullscreen

bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

bind=SUPER,n,focusstack,next
bind=SUPER,p,focusstack,prev

bind=SUPER,BackSpace,zoom
bind=SUPER,space,switch_layout

bind=SUPER,a,incnmaster,+1
bind=SUPER,x,incnmaster,-1
bind=SUPER+CTRL,a,setmfact,+0.5
bind=SUPER+CTRL,x,setmfact,-0.5

# Layouts
bind=SUPER,t,setlayout,tile
bind=SUPER+SHIFT,t,setlayout,right_tile
bind=SUPER+CTRL,t,setlayout,vertical_tile
bind=SUPER,c,setlayout,deck
bind=SUPER+CTRL,c,setlayout,vertical_deck
bind=SUPER,m,setlayout,monocle
bind=SUPER,z,setlayout,center_tile

# Tags
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8

bind=SUPER+SHIFT,1,tagsilent,1
bind=SUPER+SHIFT,2,tagsilent,2
bind=SUPER+SHIFT,3,tagsilent,3
bind=SUPER+SHIFT,4,tagsilent,4
bind=SUPER+SHIFT,5,tagsilent,5
bind=SUPER+SHIFT,6,tagsilent,6
bind=SUPER+SHIFT,7,tagsilent,7
bind=SUPER+SHIFT,8,tagsilent,8

bind=SUPER,Tab,view,-1
bind=SUPER,comma,viewtoleft
bind=SUPER,period,viewtoright

# Spawners
bind=SUPER,Return,spawn,buttermilk
bind=SUPER,d,spawn,rofi -show drun
bind=SUPER,w,spawn,firefox

# Volume Control
bind=NONE,XF86AudioRaiseVolume,spawn_shell,pactl set-sink-volume @DEFAULT_SINK@ +5% && canberra-gtk-play -i audio-volume-change
bind=NONE,XF86AudioLowerVolume,spawn_shell,pactl set-sink-volume @DEFAULT_SINK@ -5% && canberra-gtk-play -i audio-volume-change
bind=NONE,XF86AudioMute,spawn,pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=NONE,XF86AudioMicMute,spawn,pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind=SUPER,bracketright,spawn_shell,pactl set-sink-volume @DEFAULT_SINK@ +5% && canberra-gtk-play -i audio-volume-change
bind=SUPER,bracketleft,spawn_shell,pactl set-sink-volume @DEFAULT_SINK@ -5% && canberra-gtk-play -i audio-volume-change
bind=SUPER,backslash,spawn,pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=SUPER+SHIFT,backslash,spawn,pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Media Control
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause -p Lollypop,rhythmbox,spotify,cliamp
bind=NONE,XF86AudioPause,spawn,playerctl play-pause -p Lollypop,rhythmbox,spotify,cliamp
bind=NONE,XF86AudioPrev,spawn,playerctl previous -p Lollypop,rhythmbox,spotify,cliamp
bind=NONE,XF86AudioNext,spawn,playerctl next -p Lollypop,rhythmbox,spotify,cliamp
bind=SUPER,i,spawn,playerctl play-pause -p Lollypop,rhythmbox,spotify,cliamp
bind=SUPER,u,spawn,playerctl previous -p Lollypop,rhythmbox,spotify,cliamp
bind=SUPER,o,spawn,playerctl next -p Lollypop,rhythmbox,spotify,cliamp

# Brightness Control
bind=NONE,XF86MonBrightnessUp,spawn,laptopctl backlight --inc-smooth 10
bind=NONE,XF86MonBrightnessDown,spawn,laptopctl backlight --dec-smooth 10

Monitors
bind=NONE,XF86Display,spawn,wdisplays


### MOUSE & GESTURE BINDINGS ###
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER+SHIFT,btn_middle,killclient

gesturebind=NONE,left,3,viewtoright_have_client
gesturebind=NONE,right,3,viewtoleft_have_client
gesturebind=NONE,left,4,viewtoright
gesturebind=NONE,right,4,viewtoleft
gesturebind=NONE,up,3,spawn,rofi -show drun
gesturebind=NONE,down,3,spawn,pkill -2 rofi


### LAPTOP SWITCH BINDINGS ###
switchbind=fold,spawn,lock-screen-wl
