# Games
windowrule=force_tearing:1,title:Counter-Strike 2

# Floating
windowrule=isfloating:1,appid:spic-vm

# Overlay/Ignored
windowrule=isoverlay:1,isfloating:1,isunglobal:1,isnoborder:1,appid:com.nextcloud.desktopclient.nextcloud,title:Nextcloud
windowrule=isoverlay:1,isfloating:1,isunglobal:1,isnoborder:1,offsetx:0,offsety:0,appid:papaya-widget

# Workspaces
windowrule=tags:5,appid:thunderbird
windowrule=tags:6,appid:steam
windowrule=tags:6,title:Steam
windowrule=tags:7,title:Discord
