name: iso

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '30 3 * * 1' # runs weekly on Monday at 03:30

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4
    - name: 'Install Nix'
      uses: DeterminateSystems/nix-installer-action@main
    - name: 'Setup Nix cache'
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: 'Build iso'
      run: nix build .#live-iso-x86_64 -o result-x86_64
    - name: 'Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        name: live-iso-x86_64
        path: ./result-x86_64/iso/*.iso
        retention-days: 7
